Repository lum-network/explorer, pull requests merged in 2021-12, with the labels that each got.

#48 [LUM-309] Add Unjail message
  src/constant/enums/MessagesType.ts
  src/locales/locales/en.ts
  src/models/models/message.ts
  src/models/models/transactions.ts
  src/pages/pages/Transactions/show/TransactionPage.tsx
  src/utils/utils/messages.ts
Labels: Coldfix

#49 [LUM-FIXES] Fix wordings
  .github/workflows/merge.yml
  .github/workflows/pull_request.yml
  src/locales/locales/en.ts
  src/pages/pages/Accounts/Accounts.scss
  src/pages/pages/Accounts/show/AccountPage.tsx
Labels: Coldfix

#50 Bring changes to production
  .github/workflows/merge.yml
  .github/workflows/pull_request.yml
  src/locales/locales/en.ts
  src/pages/pages/Accounts/Accounts.scss
  src/pages/pages/Accounts/show/AccountPage.tsx
Labels: Production ready

#52 [LUM-302] Fix proposal tab
  src/pages/pages/Proposals/list/ProposalsPage.tsx
  src/pages/pages/Proposals/show/ProposalPage.tsx
  src/redux/models/models/core.ts
  yarn.lock
Labels: Coldfix, Improvement

#53 Bring changes to production
  src/pages/pages/Proposals/list/ProposalsPage.tsx
  src/pages/pages/Proposals/show/ProposalPage.tsx
  src/redux/models/models/core.ts
  yarn.lock
Labels: Production ready

#51 [LUM-281] Add Lum price
  .eslintrc.js
  src/api/index.ts
  src/constant/constant/api.ts
  src/core/index.tsx
  src/locales/locales/en.ts
  src/models/index.ts
  src/models/models/lum.ts
  src/pages/pages/Accounts/show/AccountPage.tsx
  src/pages/pages/Home/components/Lum/Lum.tsx
  src/redux/models/models/core.ts
  src/utils/index.ts
  src/utils/utils/http.ts
  src/utils/utils/numbers.tsx
Labels: Feature
