Repository lum-network/explorer, pull requests merged in 2021-09, with the labels that each got.

#23 [LUM-217] Handle block not found
  src/App.tsx
  src/assets/images/placeholderTx.svg
  src/hoc/index.ts
  src/locales/locales/en.ts
  src/pages/pages/Blocks/show/BlockPage.tsx
Labels: Improvement

#26 [LUM-216] Handle account not found
  src/locales/locales/en.ts
  src/pages/pages/Accounts/show/AccountPage.tsx
Labels: Improvement

#25 [LUM-218] Handle validator not found
  src/locales/locales/en.ts
  src/pages/pages/Validators/show/ValidatorPage.tsx
  src/redux/models/models/validators.ts
Labels: Improvement

#27 [LUM-234] Little fixes
  src/assets/images/placeholderValidator.svg
  src/pages/pages/Blocks/show/BlockPage.tsx
  src/pages/pages/Validators/Validators.scss
  src/pages/pages/Validators/list/ValidatorsPage.tsx
  src/pages/pages/Validators/show/ValidatorPage.tsx
  src/redux/models/models/validators.ts
Labels: Coldfix

#24 [LUM-219] Add news cards to Dashboard
  package.json
  src/api/api/stats.ts
  src/api/index.ts
  src/assets/images/inflationDark.svg
  src/components/components/kpi/Kpi/Kpi.tsx
  src/constant/constant/api.ts
  src/constant/enums/KpiType.ts
  src/core/index.tsx
  src/layout/layout/MainLayout/MainLayout.scss
  src/layout/layout/MainLayout/MainLayout.tsx
  src/locales/locales/en.ts
  src/models/index.ts
  src/models/models/stats.ts
  src/pages/pages/Accounts/show/AccountPage.tsx
  src/pages/pages/Home/HomePage.tsx
  src/redux/models/index.ts
  src/redux/models/models/blocks.ts
  src/redux/models/models/core.ts
  src/redux/store/index.ts
  yarn.lock
Labels: Improvement

#30 [LUM-240] Add commission in Account details page
  src/models/models/account.ts
  src/pages/pages/Accounts/Accounts.scss
  src/pages/pages/Accounts/show/AccountPage.tsx
Labels: Improvement

#31 Bringe changes to production
  .github/workflows/merge.yml
  package.json
  src/App.tsx
  src/api/api/stats.ts
  src/api/index.ts
  src/assets/images/inflationDark.svg
  src/assets/images/placeholderTx.svg
  src/assets/images/placeholderValidator.svg
  src/components/components/kpi/Kpi/Kpi.tsx
  src/constant/constant/api.ts
  src/constant/enums/KpiType.ts
  src/core/index.tsx
  src/hoc/index.ts
  src/layout/layout/MainLayout/MainLayout.scss
  src/layout/layout/MainLayout/MainLayout.tsx
  src/locales/locales/en.ts
  src/models/index.ts
  src/models/models/account.ts
  src/models/models/stats.ts
  src/pages/pages/Accounts/Accounts.scss
  src/pages/pages/Accounts/show/AccountPage.tsx
  src/pages/pages/Blocks/show/BlockPage.tsx
  src/pages/pages/Home/HomePage.tsx
  src/pages/pages/Validators/Validators.scss
  src/pages/pages/Validators/list/ValidatorsPage.tsx
  src/pages/pages/Validators/show/ValidatorPage.tsx
  src/redux/models/index.ts
  src/redux/models/models/blocks.ts
  src/redux/models/models/core.ts
  src/redux/models/models/validators.ts
  src/redux/store/index.ts
  yarn.lock
Labels: Production ready

#29 [LUM-214] Governance messages display
  src/assets/images/messageTypes/deposit.svg
  src/assets/images/messageTypes/redelegate.svg
  src/assets/images/messageTypes/submitProposal.svg
  src/assets/images/messageTypes/unjail.svg
  src/assets/images/messageTypes/vote.svg
  src/components/components/VoteOption/VoteOption.scss
  src/components/components/VoteOption/VoteOption.tsx
  src/components/index.ts
  src/constant/constant/navigation.ts
  src/constant/enums/MessagesType.ts
  src/constant/enums/VotesOption.ts
  src/constant/index.ts
  src/locales/locales/en.ts
  src/models/models/coin.ts
  src/models/models/message.ts
  src/models/models/transactions.ts
  src/pages/pages/Transactions/show/TransactionPage.tsx
  src/utils/utils/account.ts
  src/utils/utils/messages.ts
  yarn.lock
Labels: Feature
