Repository lum-network/explorer, pull requests merged in 2022-03, with the labels that each got.

#61 [LUM-358] Add Beams
  package.json
  src/api/index.ts
  src/assets/images/beamDark.svg
  src/assets/images/starEmpty.svg
  src/assets/images/starFull.svg
  src/components/components/Badge/Badge.tsx
  src/components/components/Rating/Rating.tsx
  src/components/index.ts
  src/constant/constant/api.ts
  src/constant/constant/navigation.ts
  src/constant/enums/BeamsStatus.ts
  src/constant/index.ts
  src/locales/locales/en.ts
  src/models/index.ts
  src/models/models/beam.ts
  src/models/models/message.ts
  src/navigation/index.tsx
  src/pages/index.ts
  src/pages/pages/Beams/Beams.scss
  src/pages/pages/Beams/list/BeamsPage.tsx
  src/pages/pages/Beams/show/BeamPage.tsx
  src/pages/pages/Transactions/show/TransactionPage.tsx
  src/redux/models/index.ts
  src/redux/models/models/accounts.ts
  src/redux/models/models/beams.ts
  src/redux/models/models/blocks.ts
  src/redux/models/models/core.ts
  src/redux/models/models/governance.ts
  src/redux/models/models/search.ts
  src/redux/models/models/transactions.ts
  src/redux/models/models/validators.ts
  yarn.lock
Labels: Feature

#64 [LUM-366] Remove persistor
  package.json
  src/App.tsx
  src/redux/store/index.ts
  yarn.lock
Labels: Coldfix

#62 Added react Sentry integration
  .env
  .env.example
  .github/workflows/merge.yml
  .gitignore
  package.json
  src/index.tsx
  yarn.lock
Labels: Improvement

#65 Bring changes to production
  .env
  .env.example
  .github/workflows/merge.yml
  .gitignore
  package.json
  src/App.tsx
  src/index.tsx
  src/redux/store/index.ts
  yarn.lock
Labels: Production ready
